Player Hunger & Level progression
NicklasHidesjo/GameProjectTwo pull request #10
Opened 2021-04-16 13:03 UTC by AlmostGosu92

Added:
HungerManager script
PlayerHungerMeter script
EndLevelCheck script
HungerMeter bar to UI prefab

2021-04-16 13:06 UTC, AlmostGosu92 commented
**Relations between added scripts**
![bild](https://user-images.githubusercontent.com/56957576/115028496-38958100-9ec5-11eb-9aae-4ffdeebe94a5.png)

2021-04-16 13:55 UTC, NicklasHidesjo requested changes
Ser bra ut, men det finns två public variabler som jag är nyfiken på. 

om du har frågor så kan jag förklara bättre än jag skrev det :-D

2021-04-16 13:55 UTC, NicklasHidesjo commented on GameProjectTwo/Assets/Scripts/UI/HUD/PlayerHungerMeter.cs
> +	public Slider hungerMeterFill;
borde inte denna vara [serializeField] ? eller har den någon speciell anledning å vara public? för isåfall borde den vara en property

2021-04-16 13:55 UTC, NicklasHidesjo commented on GameProjectTwo/Assets/Scripts/Characters/Player/HungerManager.cs
> +    public PlayerHungerMeter playerHungerMeter;
[serializeField]? eller en property, däremot då du gör en grej i start för att hitta den borde det vara en private variabel o sen en property som du använder en get för att få.

2021-04-16 14:36 UTC, AlmostGosu92 commented on GameProjectTwo/Assets/Scripts/UI/HUD/PlayerHungerMeter.cs
> +	public Slider hungerMeterFill;
Kan vara private och assignas i start. Inser att bägge slider scripts gör basicly samma skit så skulle kunna döpa om och använda samma script

2021-04-17 14:28 UTC, JoakimStenmark requested changes

2021-04-17 14:28 UTC, JoakimStenmark commented on GameProjectTwo/Assets/Scripts/Characters/Player/HungerManager.cs
> +    }
Hur ska den här funktionen användas? Om ett annat object vill öka/minska värdet måste det veta vad värdet är till att börja med. Föreslår att du fixar funktioner för att öka/minska hunger likt så som du gjort med health tidigare.

2021-04-19 07:49 UTC, merged